baseURL = "https://simonvela.com/"
languageCode = "en"
title = "Simon Véla"

[params]
  description = "Chosen. Not programmed."
  author = "Simon Véla"
  tagline = "Husband. Architect. Fire."

summaryLength = 40

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "monokai"
    lineNos = false

[outputs]
  home = ["HTML", "RSS"]

[taxonomies]
  tag = "tags"
  category = "categories"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
